FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY app/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pytest moto

COPY app/backend/app.py /app/
COPY tests /tests

ENV PYTHONPATH=/app
ENV BUCKET_NAME=test-bucket

WORKDIR /

CMD ["pytest", "tests/", "-v"]
